docs_dir: doc/book/ru
pages:
    - index.md
    - 'Общие понятия': 'common-description.md'
    - 'Менеджер для получения Resolver ов': 'entry-name-resolver-manager.md'
    - 'Resolver s':
      - 'EntryNameResolverChain': 'entry-name-resolver-chain.md'
      - 'ResolverByModuleContextMap': 'resolver-by-module-context-map.md'
      - 'ResolverByClassName': 'resolver-by-class-name.md'
site_name: container
site_description: 'Определение имени сервиса(компонента и.т.д) в зависимости от контекста вызова'
repo_url: 'https://github.com/nnx-framework/entry-name-resolver'
copyright: 'Copyright (c) 2016 <a href="https://github.com/nnx-framework">NNX</a>'
